name: Run Unit Tests

on:
  push:
    branches: [ main ]  # Will only be executed on main branch for now

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  K
- name: Set up JDK 8
  uses: actions/setup-java@v3
  with:
    java-version: '8'
    distribution: 'temurin'

- name: Build and Test
  run: mvn clean test
